In [1]:
import pandas as pd

In [98]:
data = pd.read_parquet('newyork_procesado_completo.parquet')

In [99]:
data.shape

(70444, 35)

In [100]:
pd.set_option('display.max_columns', 200)

In [101]:
data.head()

,identificador,name,address,category,latitude,longitude,avg_rating,hours,reviews,source,line,Automotive,Shopping,Health and Hospitals,Rental Services,Health and Beauty,Entertainment,Restaurants,Tourism,Veterinary and Pets,Education and Learning,Sports,Arts and Crafts,Events and Weddings,Industry,"Technology, Networks, Electronics, and Engineering",Professional Services,Gardening and Home Services,Other,sumatoria,date_list,rating_list,text_list,labels,scores
0,0x89c25c4d51ce644f:0xcbe2215117d54f91,Marjorie Richardson Court,"Marjorie Richardson Court, 359 Hendrix St, Bro...",[Property management company],40.673296,-73.889258,3.7,"{""Monday"": ""No information"", ""Tuesday"": ""No in...","[{'date': '2020-01-21', 'rating': 5.0, 'text':...",gmap,Rental Services,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-01-21, 2019-03-24, 2018-08-17, 2017-11-2...","[5.0, 3.0, 4.0, 3.0, 5.0, 5.0, 3.0, 4.0, 1.0, ...","[None, None, Beautiful and spacious, None, Non...","[None, None, POSITIVE, None, None, None, None,...","[nan, nan, 0.9998843669891357, nan, nan, nan, ..."
1,0x89e898cce91819e5:0x78295632ec3d9958,The Peconic Star Express,"The Peconic Star Express, 103 3rd St, Greenpor...",[Fishing charter],41.100001,-72.362260,4.5,"{""Thursday"": ""7:30 AM-3 PM"", ""Friday"": ""7:30 A...","[{'date': '2018-08-02', 'rating': 5.0, 'text':...",gmap,Tourism,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2018-08-02, 2017-08-14, 2018-08-25, 2018-08-2...","[5.0, 1.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0, ...","[None, Beware. It seems most everybody on the ...","[None, NEGATIVE, None, POSITIVE, None, None, P...","[nan, 0.9909191131591797, nan, 0.9998655319213..."
2,0x89de71bbf856c4e1:0x7c937984dc01f83d,Morizio's Barbershop,"Morizio's Barbershop, 1308 Curry Rd, Rotterdam...",[Barber shop],42.784536,-73.965524,5.0,"{""Wednesday"": ""10 AM-5 PM"", ""Thursday"": ""10 AM...","[{'date': '2020-11-05', 'rating': 5.0, 'text':...",gmap,Health and Beauty,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-11-05, 2018-01-12, 2019-08-03, 2018-02-2...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Great cut; with precision and attention to th...,"[POSITIVE, POSITIVE, POSITIVE, POSITIVE, POSIT...","[0.9998070597648621, 0.9998575448989868, 0.999..."
3,0x89c259813c908c2d:0x71afdaae24147ea9,Café d’Avignon,"Café d’Avignon, 88 Essex St, New York, NY 10002","[Bakery, Cafe, Coffee shop, Pastry shop, Sandw...",40.718241,-73.988107,4.3,"{""Sunday"": ""10 AM-6 PM"", ""Monday"": ""8 AM-7 PM""...","[{'date': '2012-09-22', 'rating': 4.0, 'text':...",gmap,Restaurants,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2012-09-22, 2021-01-31, 2021-05-06, 2016-05-1...","[4.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 3.0, 5.0, ...",[Excellent pastries that are the right mix of ...,"[POSITIVE, POSITIVE, POSITIVE, POSITIVE, POSIT...","[0.9998525381088257, 0.9993057250976562, 0.999..."
4,0x89c25a2a7d0c286d:0x964aba5910880a95,Jerrold F. Heller & Associates D.D.S.,"Jerrold F. Heller & Associates D.D.S., 425 Gra...","[Dentist, Endodontist, Periodontist]",40.715512,-73.986171,4.9,"{""Tuesday"": ""9 AM-5 PM"", ""Wednesday"": ""7 AM-2 ...","[{'date': '2020-02-20', 'rating': 5.0, 'text':...",gmap,Health and Hospitals,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-02-20, 2020-02-21, 2021-02-18, 2020-08-0...","[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Very nice office + receptionists and I receiv...,"[POSITIVE, None, None, POSITIVE, POSITIVE, POS...","[0.5163335204124451, nan, nan, 0.9979732632637..."

In [102]:
data.labels[500]

array(['POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE',
       'POSITIVE', None, None, 'POSITIVE', 'POSITIVE', 'POSITIVE',
       'POSITIVE', None, 'POSITIVE', 'POSITIVE', 'POSITIVE', 'NEGATIVE',
       'POSITIVE', 'NEGATIVE', None, 'NEGATIVE', None, 'POSITIVE',
       'POSITIVE', None, 'POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE',
       'POSITIVE', None, None, 'POSITIVE', 'NEGATIVE', None, 'POSITIVE',
       None, 'POSITIVE', 'POSITIVE', None, 'POSITIVE', None, None,
       'POSITIVE', 'POSITIVE', None, None, None, None, 'POSITIVE', None,
       'POSITIVE', None, 'POSITIVE', 'POSITIVE', None, 'NEGATIVE', None,
       'POSITIVE', 'POSITIVE', 'POSITIVE', None, 'NEGATIVE', None,
       'POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE', 'POSITIVE',
       'POSITIVE', 'NEGATIVE', 'POSITIVE', None, None, None, None,
       'POSITIVE', 'POSITIVE', None, None], dtype=object)

In [103]:
import numpy as np

In [104]:
# Calcular el promedio de los números en la lista de 'rating_list'
data['avg_rating_list'] = data['rating_list'].apply(lambda x: np.mean(x) if len(x) > 0 else 0)

# Calcular el porcentaje de satisfacción
data['percent_good_reviews'] = data['labels'].apply(lambda x: np.sum(x == 'POSITIVE') / np.sum((x == 'POSITIVE') | (x == 'NEGATIVE')) if ('POSITIVE' in x) or ('NEGATIVE' in x) else None)

In [105]:
data.labels[0]

array([None, None, 'POSITIVE', None, None, None, None, None, 'NEGATIVE',
       None, 'POSITIVE'], dtype=object)

In [106]:
data.percent_good_reviews[0]

0.6666666666666666

In [108]:
# Define una función para asignar categorías
def categorizar_satisfaccion(satisfaccion):
    if satisfaccion < 0.4:
        return 'Very Dissatisfied 😞'
    elif 0.40 <= satisfaccion < 0.6:
        return 'Dissatisfied 😕'
    elif 0.60 <= satisfaccion < 0.9:
        return 'Satisfied 😊'
    else:
        return 'Very Satisfied 😃'

In [109]:
# Aplicar la función a la columna "Satisfaccion" y crear una nueva columna "Categoria"
data['satisfaction'] = data['percent_good_reviews'].apply(categorizar_satisfaccion)

In [110]:
data['satisfaction'].value_counts()

satisfaction
Satisfied 😊            38862
Very Satisfied 😃       22812
Dissatisfied 😕          6380
Very Dissatisfied 😞     2390
Name: count, dtype: int64

In [111]:
data.head()

,identificador,name,address,category,latitude,longitude,avg_rating,hours,reviews,source,line,Automotive,Shopping,Health and Hospitals,Rental Services,Health and Beauty,Entertainment,Restaurants,Tourism,Veterinary and Pets,Education and Learning,Sports,Arts and Crafts,Events and Weddings,Industry,"Technology, Networks, Electronics, and Engineering",Professional Services,Gardening and Home Services,Other,sumatoria,date_list,rating_list,text_list,labels,scores,avg_rating_list,percent_good_reviews,satisfaction
0,0x89c25c4d51ce644f:0xcbe2215117d54f91,Marjorie Richardson Court,"Marjorie Richardson Court, 359 Hendrix St, Bro...",[Property management company],40.673296,-73.889258,3.7,"{""Monday"": ""No information"", ""Tuesday"": ""No in...","[{'date': '2020-01-21', 'rating': 5.0, 'text':...",gmap,Rental Services,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-01-21, 2019-03-24, 2018-08-17, 2017-11-2...","[5.0, 3.0, 4.0, 3.0, 5.0, 5.0, 3.0, 4.0, 1.0, ...","[None, None, Beautiful and spacious, None, Non...","[None, None, POSITIVE, None, None, None, None,...","[nan, nan, 0.9998843669891357, nan, nan, nan, ...",3.727273,0.666667,Satisfied 😊
1,0x89e898cce91819e5:0x78295632ec3d9958,The Peconic Star Express,"The Peconic Star Express, 103 3rd St, Greenpor...",[Fishing charter],41.100001,-72.362260,4.5,"{""Thursday"": ""7:30 AM-3 PM"", ""Friday"": ""7:30 A...","[{'date': '2018-08-02', 'rating': 5.0, 'text':...",gmap,Tourism,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2018-08-02, 2017-08-14, 2018-08-25, 2018-08-2...","[5.0, 1.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0, ...","[None, Beware. It seems most everybody on the ...","[None, NEGATIVE, None, POSITIVE, None, None, P...","[nan, 0.9909191131591797, nan, 0.9998655319213...",4.629630,0.666667,Satisfied 😊
2,0x89de71bbf856c4e1:0x7c937984dc01f83d,Morizio's Barbershop,"Morizio's Barbershop, 1308 Curry Rd, Rotterdam...",[Barber shop],42.784536,-73.965524,5.0,"{""Wednesday"": ""10 AM-5 PM"", ""Thursday"": ""10 AM...","[{'date': '2020-11-05', 'rating': 5.0, 'text':...",gmap,Health and Beauty,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-11-05, 2018-01-12, 2019-08-03, 2018-02-2...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Great cut; with precision and attention to th...,"[POSITIVE, POSITIVE, POSITIVE, POSITIVE, POSIT...","[0.9998070597648621, 0.9998575448989868, 0.999...",5.000000,0.941176,Very Satisfied 😃
3,0x89c259813c908c2d:0x71afdaae24147ea9,Café d’Avignon,"Café d’Avignon, 88 Essex St, New York, NY 10002","[Bakery, Cafe, Coffee shop, Pastry shop, Sandw...",40.718241,-73.988107,4.3,"{""Sunday"": ""10 AM-6 PM"", ""Monday"": ""8 AM-7 PM""...","[{'date': '2012-09-22', 'rating': 4.0, 'text':...",gmap,Restaurants,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2012-09-22, 2021-01-31, 2021-05-06, 2016-05-1...","[4.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 3.0, 5.0, ...",[Excellent pastries that are the right mix of ...,"[POSITIVE, POSITIVE, POSITIVE, POSITIVE, POSIT...","[0.9998525381088257, 0.9993057250976562, 0.999...",4.312500,0.933333,Very Satisfied 😃
4,0x89c25a2a7d0c286d:0x964aba5910880a95,Jerrold F. Heller & Associates D.D.S.,"Jerrold F. Heller & Associates D.D.S., 425 Gra...","[Dentist, Endodontist, Periodontist]",40.715512,-73.986171,4.9,"{""Tuesday"": ""9 AM-5 PM"", ""Wednesday"": ""7 AM-2 ...","[{'date': '2020-02-20', 'rating': 5.0, 'text':...",gmap,Health and Hospitals,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"[2020-02-20, 2020-02-21, 2021-02-18, 2020-08-0...","[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Very nice office + receptionists and I receiv...,"[POSITIVE, None, None, POSITIVE, POSITIVE, POS...","[0.5163335204124451, nan, nan, 0.9979732632637...",4.909091,1.000000,Very Satisfied 😃

In [112]:
data.columns

Index(['identificador', 'name', 'address', 'category', 'latitude', 'longitude',
       'avg_rating', 'hours', 'reviews', 'source', 'line', 'Automotive',
       'Shopping', 'Health and Hospitals', 'Rental Services',
       'Health and Beauty', 'Entertainment', 'Restaurants', 'Tourism',
       'Veterinary and Pets', 'Education and Learning', 'Sports',
       'Arts and Crafts', 'Events and Weddings', 'Industry',
       'Technology, Networks, Electronics, and Engineering',
       'Professional Services', 'Gardening and Home Services', 'Other',
       'sumatoria', 'date_list', 'rating_list', 'text_list', 'labels',
       'scores', 'avg_rating_list', 'percent_good_reviews', 'satisfaction'],
      dtype='object')

In [113]:
selected_columns = ['identificador', 'name', 'address', 'latitude', 'longitude',
       'avg_rating', 'hours', 'reviews', 'source', 'line', 'Automotive',
       'Shopping', 'Health and Hospitals', 'Rental Services',
       'Health and Beauty', 'Entertainment', 'Restaurants', 'Tourism',
       'Veterinary and Pets', 'Education and Learning', 'Sports',
       'Arts and Crafts', 'Events and Weddings', 'Industry',
       'Technology, Networks, Electronics, and Engineering',
       'Professional Services', 'Gardening and Home Services', 'Other',
       'sumatoria', 'date_list', 'rating_list', 'text_list', 'labels',
       'scores', 'avg_rating_list', 'percent_good_reviews', 'satisfaction']

In [114]:
data = data[selected_columns]

In [115]:
data.shape

(70444, 37)

In [116]:
data.columns

Index(['identificador', 'name', 'address', 'latitude', 'longitude',
       'avg_rating', 'hours', 'reviews', 'source', 'line', 'Automotive',
       'Shopping', 'Health and Hospitals', 'Rental Services',
       'Health and Beauty', 'Entertainment', 'Restaurants', 'Tourism',
       'Veterinary and Pets', 'Education and Learning', 'Sports',
       'Arts and Crafts', 'Events and Weddings', 'Industry',
       'Technology, Networks, Electronics, and Engineering',
       'Professional Services', 'Gardening and Home Services', 'Other',
       'sumatoria', 'date_list', 'rating_list', 'text_list', 'labels',
       'scores', 'avg_rating_list', 'percent_good_reviews', 'satisfaction'],
      dtype='object')

In [73]:
#data.to_parquet('florida_dashboard_reco.parquet', index=False)

In [117]:
data.date_list[0]

array(['2020-01-21', '2019-03-24', '2018-08-17', '2017-11-21',
       '2017-03-01', '2020-02-19', '2017-09-06', '2018-08-29',
       '2021-01-10', '2019-08-27', '2018-06-18'], dtype=object)

In [118]:
# Convierte cada lista de fechas a tipo datetime y guarda el resultado en una nueva columna
data['date_list'] = data['date_list'].apply(lambda x: [pd.to_datetime(date) for date in x])

# Calcula la fecha más antigua en cada lista y guárdala en 'earliest_review'
data['earliest_review'] = data['date_list'].apply(lambda x: min(x))

# Calcula la fecha más actual en cada lista y guárdala en 'latest_review'
data['latest_review'] = data['date_list'].apply(lambda x: max(x))

In [119]:
data.date_list[0]

[Timestamp('2020-01-21 00:00:00'),
 Timestamp('2019-03-24 00:00:00'),
 Timestamp('2018-08-17 00:00:00'),
 Timestamp('2017-11-21 00:00:00'),
 Timestamp('2017-03-01 00:00:00'),
 Timestamp('2020-02-19 00:00:00'),
 Timestamp('2017-09-06 00:00:00'),
 Timestamp('2018-08-29 00:00:00'),
 Timestamp('2021-01-10 00:00:00'),
 Timestamp('2019-08-27 00:00:00'),
 Timestamp('2018-06-18 00:00:00')]

In [120]:
data['earliest_review'][0]

Timestamp('2017-03-01 00:00:00')

In [121]:
data['latest_review'][0]

Timestamp('2021-01-10 00:00:00')

In [122]:
data['earliest_review'] = data['earliest_review'].dt.strftime('%Y-%m-%d')
data['latest_review'] = data['latest_review'].dt.strftime('%Y-%m-%d')

In [124]:
data.columns

Index(['identificador', 'name', 'address', 'latitude', 'longitude',
       'avg_rating', 'hours', 'reviews', 'source', 'line', 'Automotive',
       'Shopping', 'Health and Hospitals', 'Rental Services',
       'Health and Beauty', 'Entertainment', 'Restaurants', 'Tourism',
       'Veterinary and Pets', 'Education and Learning', 'Sports',
       'Arts and Crafts', 'Events and Weddings', 'Industry',
       'Technology, Networks, Electronics, and Engineering',
       'Professional Services', 'Gardening and Home Services', 'Other',
       'sumatoria', 'date_list', 'rating_list', 'text_list', 'labels',
       'scores', 'avg_rating_list', 'percent_good_reviews', 'satisfaction',
       'earliest_review', 'latest_review'],
      dtype='object')

In [126]:
selected_columns = ['identificador', 'name', 'address', 'latitude', 'longitude',
       'avg_rating', 'hours', 'source', 'line','satisfaction',
       'earliest_review', 'latest_review', 'Automotive',
       'Shopping', 'Health and Hospitals', 'Rental Services',
       'Health and Beauty', 'Entertainment', 'Restaurants', 'Tourism',
       'Veterinary and Pets', 'Education and Learning', 'Sports',
       'Arts and Crafts', 'Events and Weddings', 'Industry',
       'Technology, Networks, Electronics, and Engineering',
       'Professional Services', 'Gardening and Home Services', 'Other',
       'sumatoria', 'date_list', 'rating_list', 'text_list', 'labels',
       'scores', 'avg_rating_list', 'percent_good_reviews']

In [127]:
data = data[selected_columns]

In [128]:
data.to_parquet('newyork_dashboard_reco_date.parquet', index=False)